// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FLATSQLATTR_FLATSQL_PS_FB_H_
#define FLATBUFFERS_GENERATED_FLATSQLATTR_FLATSQL_PS_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace flatsql {
namespace ps {
namespace fb {

struct SourceTag;
struct SourceTagBuilder;

struct RecordAttr;
struct RecordAttrBuilder;

struct SourceTag FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SourceTagBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROVIDER_ID = 4,
    VT_SOURCE_NAME = 6,
    VT_SOURCE_URL = 8,
    VT_BATCH_ID = 10,
    VT_CONTENT_KEY_ID = 12,
    VT_PRODUCER_PEER_ID = 14,
    VT_PRODUCER_PUBLIC_KEY = 16
  };
  const ::flatbuffers::String *provider_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROVIDER_ID);
  }
  const ::flatbuffers::String *source_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_NAME);
  }
  const ::flatbuffers::String *source_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_URL);
  }
  const ::flatbuffers::String *batch_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BATCH_ID);
  }
  const ::flatbuffers::String *content_key_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTENT_KEY_ID);
  }
  const ::flatbuffers::String *producer_peer_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PRODUCER_PEER_ID);
  }
  const ::flatbuffers::String *producer_public_key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PRODUCER_PUBLIC_KEY);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PROVIDER_ID) &&
           verifier.VerifyString(provider_id()) &&
           VerifyOffset(verifier, VT_SOURCE_NAME) &&
           verifier.VerifyString(source_name()) &&
           VerifyOffset(verifier, VT_SOURCE_URL) &&
           verifier.VerifyString(source_url()) &&
           VerifyOffset(verifier, VT_BATCH_ID) &&
           verifier.VerifyString(batch_id()) &&
           VerifyOffset(verifier, VT_CONTENT_KEY_ID) &&
           verifier.VerifyString(content_key_id()) &&
           VerifyOffset(verifier, VT_PRODUCER_PEER_ID) &&
           verifier.VerifyString(producer_peer_id()) &&
           VerifyOffset(verifier, VT_PRODUCER_PUBLIC_KEY) &&
           verifier.VerifyString(producer_public_key()) &&
           verifier.EndTable();
  }
};

struct SourceTagBuilder {
  typedef SourceTag Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_provider_id(::flatbuffers::Offset<::flatbuffers::String> provider_id) {
    fbb_.AddOffset(SourceTag::VT_PROVIDER_ID, provider_id);
  }
  void add_source_name(::flatbuffers::Offset<::flatbuffers::String> source_name) {
    fbb_.AddOffset(SourceTag::VT_SOURCE_NAME, source_name);
  }
  void add_source_url(::flatbuffers::Offset<::flatbuffers::String> source_url) {
    fbb_.AddOffset(SourceTag::VT_SOURCE_URL, source_url);
  }
  void add_batch_id(::flatbuffers::Offset<::flatbuffers::String> batch_id) {
    fbb_.AddOffset(SourceTag::VT_BATCH_ID, batch_id);
  }
  void add_content_key_id(::flatbuffers::Offset<::flatbuffers::String> content_key_id) {
    fbb_.AddOffset(SourceTag::VT_CONTENT_KEY_ID, content_key_id);
  }
  void add_producer_peer_id(::flatbuffers::Offset<::flatbuffers::String> producer_peer_id) {
    fbb_.AddOffset(SourceTag::VT_PRODUCER_PEER_ID, producer_peer_id);
  }
  void add_producer_public_key(::flatbuffers::Offset<::flatbuffers::String> producer_public_key) {
    fbb_.AddOffset(SourceTag::VT_PRODUCER_PUBLIC_KEY, producer_public_key);
  }
  explicit SourceTagBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SourceTag> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SourceTag>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SourceTag> CreateSourceTag(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> provider_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_url = 0,
    ::flatbuffers::Offset<::flatbuffers::String> batch_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> content_key_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> producer_peer_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> producer_public_key = 0) {
  SourceTagBuilder builder_(_fbb);
  builder_.add_producer_public_key(producer_public_key);
  builder_.add_producer_peer_id(producer_peer_id);
  builder_.add_content_key_id(content_key_id);
  builder_.add_batch_id(batch_id);
  builder_.add_source_url(source_url);
  builder_.add_source_name(source_name);
  builder_.add_provider_id(provider_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SourceTag> CreateSourceTagDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *provider_id = nullptr,
    const char *source_name = nullptr,
    const char *source_url = nullptr,
    const char *batch_id = nullptr,
    const char *content_key_id = nullptr,
    const char *producer_peer_id = nullptr,
    const char *producer_public_key = nullptr) {
  auto provider_id__ = provider_id ? _fbb.CreateString(provider_id) : 0;
  auto source_name__ = source_name ? _fbb.CreateString(source_name) : 0;
  auto source_url__ = source_url ? _fbb.CreateString(source_url) : 0;
  auto batch_id__ = batch_id ? _fbb.CreateString(batch_id) : 0;
  auto content_key_id__ = content_key_id ? _fbb.CreateString(content_key_id) : 0;
  auto producer_peer_id__ = producer_peer_id ? _fbb.CreateString(producer_peer_id) : 0;
  auto producer_public_key__ = producer_public_key ? _fbb.CreateString(producer_public_key) : 0;
  return flatsql::ps::fb::CreateSourceTag(
      _fbb,
      provider_id__,
      source_name__,
      source_url__,
      batch_id__,
      content_key_id__,
      producer_peer_id__,
      producer_public_key__);
}

struct RecordAttr FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RecordAttrBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PEER_ID = 4,
    VT_SIGNATURE = 6,
    VT_SUPERSEDE_KEY = 8,
    VT_SOURCE_TIMESTAMP = 10,
    VT_LICENCE_KEY = 12,
    VT_TAGS = 14
  };
  const ::flatbuffers::Vector<uint8_t> *peer_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PEER_ID);
  }
  const ::flatbuffers::Vector<uint8_t> *signature() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_SIGNATURE);
  }
  const ::flatbuffers::String *supersede_key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SUPERSEDE_KEY);
  }
  int64_t source_timestamp() const {
    return GetField<int64_t>(VT_SOURCE_TIMESTAMP, 0);
  }
  const ::flatbuffers::String *licence_key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LICENCE_KEY);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<flatsql::ps::fb::SourceTag>> *tags() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<flatsql::ps::fb::SourceTag>> *>(VT_TAGS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PEER_ID) &&
           verifier.VerifyVector(peer_id()) &&
           VerifyOffset(verifier, VT_SIGNATURE) &&
           verifier.VerifyVector(signature()) &&
           VerifyOffset(verifier, VT_SUPERSEDE_KEY) &&
           verifier.VerifyString(supersede_key()) &&
           VerifyField<int64_t>(verifier, VT_SOURCE_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_LICENCE_KEY) &&
           verifier.VerifyString(licence_key()) &&
           VerifyOffset(verifier, VT_TAGS) &&
           verifier.VerifyVector(tags()) &&
           verifier.VerifyVectorOfTables(tags()) &&
           verifier.EndTable();
  }
};

struct RecordAttrBuilder {
  typedef RecordAttr Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_peer_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> peer_id) {
    fbb_.AddOffset(RecordAttr::VT_PEER_ID, peer_id);
  }
  void add_signature(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> signature) {
    fbb_.AddOffset(RecordAttr::VT_SIGNATURE, signature);
  }
  void add_supersede_key(::flatbuffers::Offset<::flatbuffers::String> supersede_key) {
    fbb_.AddOffset(RecordAttr::VT_SUPERSEDE_KEY, supersede_key);
  }
  void add_source_timestamp(int64_t source_timestamp) {
    fbb_.AddElement<int64_t>(RecordAttr::VT_SOURCE_TIMESTAMP, source_timestamp, 0);
  }
  void add_licence_key(::flatbuffers::Offset<::flatbuffers::String> licence_key) {
    fbb_.AddOffset(RecordAttr::VT_LICENCE_KEY, licence_key);
  }
  void add_tags(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<flatsql::ps::fb::SourceTag>>> tags) {
    fbb_.AddOffset(RecordAttr::VT_TAGS, tags);
  }
  explicit RecordAttrBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RecordAttr> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RecordAttr>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RecordAttr> CreateRecordAttr(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> peer_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> signature = 0,
    ::flatbuffers::Offset<::flatbuffers::String> supersede_key = 0,
    int64_t source_timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::String> licence_key = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<flatsql::ps::fb::SourceTag>>> tags = 0) {
  RecordAttrBuilder builder_(_fbb);
  builder_.add_source_timestamp(source_timestamp);
  builder_.add_tags(tags);
  builder_.add_licence_key(licence_key);
  builder_.add_supersede_key(supersede_key);
  builder_.add_signature(signature);
  builder_.add_peer_id(peer_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RecordAttr> CreateRecordAttrDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *peer_id = nullptr,
    const std::vector<uint8_t> *signature = nullptr,
    const char *supersede_key = nullptr,
    int64_t source_timestamp = 0,
    const char *licence_key = nullptr,
    const std::vector<::flatbuffers::Offset<flatsql::ps::fb::SourceTag>> *tags = nullptr) {
  auto peer_id__ = peer_id ? _fbb.CreateVector<uint8_t>(*peer_id) : 0;
  auto signature__ = signature ? _fbb.CreateVector<uint8_t>(*signature) : 0;
  auto supersede_key__ = supersede_key ? _fbb.CreateString(supersede_key) : 0;
  auto licence_key__ = licence_key ? _fbb.CreateString(licence_key) : 0;
  auto tags__ = tags ? _fbb.CreateVector<::flatbuffers::Offset<flatsql::ps::fb::SourceTag>>(*tags) : 0;
  return flatsql::ps::fb::CreateRecordAttr(
      _fbb,
      peer_id__,
      signature__,
      supersede_key__,
      source_timestamp,
      licence_key__,
      tags__);
}

inline const flatsql::ps::fb::RecordAttr *GetRecordAttr(const void *buf) {
  return ::flatbuffers::GetRoot<flatsql::ps::fb::RecordAttr>(buf);
}

inline const flatsql::ps::fb::RecordAttr *GetSizePrefixedRecordAttr(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<flatsql::ps::fb::RecordAttr>(buf);
}

inline const char *RecordAttrIdentifier() {
  return "FSRA";
}

inline bool RecordAttrBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, RecordAttrIdentifier());
}

inline bool SizePrefixedRecordAttrBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, RecordAttrIdentifier(), true);
}

template <bool B = false>
inline bool VerifyRecordAttrBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<flatsql::ps::fb::RecordAttr>(RecordAttrIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedRecordAttrBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<flatsql::ps::fb::RecordAttr>(RecordAttrIdentifier());
}

inline void FinishRecordAttrBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<flatsql::ps::fb::RecordAttr> root) {
  fbb.Finish(root, RecordAttrIdentifier());
}

inline void FinishSizePrefixedRecordAttrBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<flatsql::ps::fb::RecordAttr> root) {
  fbb.FinishSizePrefixed(root, RecordAttrIdentifier());
}

}  // namespace fb
}  // namespace ps
}  // namespace flatsql

#endif  // FLATBUFFERS_GENERATED_FLATSQLATTR_FLATSQL_PS_FB_H_
